name: CWL Syntax Check

on: [push]

jobs:
  check_syntax:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install CWL dependencies
        run: |
          python -m pip install --upgrade 'pip==23.1.2'
          python -m pip install 'cwltool==3.1.20230513155734'

      - name: Run cwltool validate
        run: |
          cd $GITHUB_WORKSPACE/CWL
          find . -name '*.cwl' | xargs -n 1 cwltool --validate --debug

